-- Corrected GRANT statement
-- Remove CREATE FUNCTION - it's included in CREATE PROCEDURE

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO INSURANCE_USER;

-- Or if you want to be more explicit, you can also grant these separately:
-- GRANT CREATE SESSION TO INSURANCE_USER;
-- GRANT CREATE TABLE TO INSURANCE_USER;
-- GRANT CREATE SEQUENCE TO INSURANCE_USER;
-- GRANT CREATE PROCEDURE TO INSURANCE_USER;
-- GRANT CREATE TRIGGER TO INSURANCE_USER;


