CREATE USER INSURANCE_USER IDENTIFIED BY Insurance123;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO INSURANCE_USER;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE FUNCTION TO INSURANCE_USER;

exit;


