DROP USER INSURANCE_USER CASCADE;

CREATE USER INSURANCE_USER IDENTIFIED BY Insurance123;

GRANT CONNECT, RESOURCE TO INSURANCE_USER;
GRANT UNLIMITED TABLESPACE TO INSURANCE_USER;
GRANT CREATE SESSION TO INSURANCE_USER;
GRANT CREATE TABLE TO INSURANCE_USER;
GRANT CREATE SEQUENCE TO INSURANCE_USER;
GRANT CREATE PROCEDURE TO INSURANCE_USER;
GRANT CREATE TRIGGER TO INSURANCE_USER;
GRANT CREATE FUNCTION TO INSURANCE_USER;

ALTER SESSION SET CURRENT_SCHEMA = INSURANCE_USER;


COMMIT;


