BEGIN
   EXECUTE IMMEDIATE 'CREATE USER INSURANCE_USER IDENTIFIED BY Insurance123';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -1920 THEN
         NULL;
      ELSE
         RAISE;
      END IF;
END;
/

GRANT CONNECT, RESOURCE TO INSURANCE_USER;
GRANT UNLIMITED TABLESPACE TO INSURANCE_USER;
GRANT CREATE SESSION TO INSURANCE_USER;
GRANT CREATE TABLE TO INSURANCE_USER;
GRANT CREATE SEQUENCE TO INSURANCE_USER;
GRANT CREATE PROCEDURE TO INSURANCE_USER;
GRANT CREATE TRIGGER TO INSURANCE_USER;
GRANT CREATE FUNCTION TO INSURANCE_USER;

ALTER SESSION SET CURRENT_SCHEMA = INSURANCE_USER;

@@schema.sql

@@seed.sql

COMMIT;

